/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pyuron/gesture/gesture.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pyuron_gesture_GestureInfo, pyuron_gesture_GestureInfo, AUTO)


PB_BIND(pyuron_gesture_GetCountRequest, pyuron_gesture_GetCountRequest, AUTO)


PB_BIND(pyuron_gesture_GetCountResponse, pyuron_gesture_GetCountResponse, AUTO)


PB_BIND(pyuron_gesture_GetGestureRequest, pyuron_gesture_GetGestureRequest, AUTO)


PB_BIND(pyuron_gesture_GetGestureResponse, pyuron_gesture_GetGestureResponse, AUTO)


PB_BIND(pyuron_gesture_SetParamRequest, pyuron_gesture_SetParamRequest, AUTO)


PB_BIND(pyuron_gesture_SetParamResponse, pyuron_gesture_SetParamResponse, AUTO)


PB_BIND(pyuron_gesture_ResetGestureRequest, pyuron_gesture_ResetGestureRequest, AUTO)


PB_BIND(pyuron_gesture_ResetGestureResponse, pyuron_gesture_ResetGestureResponse, AUTO)


PB_BIND(pyuron_gesture_Request, pyuron_gesture_Request, AUTO)


PB_BIND(pyuron_gesture_ErrorResponse, pyuron_gesture_ErrorResponse, AUTO)


PB_BIND(pyuron_gesture_Response, pyuron_gesture_Response, AUTO)





