/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PYURON_GESTURE_PYURON_GESTURE_GESTURE_PB_H_INCLUDED
#define PB_PYURON_GESTURE_PYURON_GESTURE_GESTURE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pyuron_gesture_Param {
    pyuron_gesture_Param_PARAM_TICK = 0,
    pyuron_gesture_Param_PARAM_WAIT_MS = 1,
    pyuron_gesture_Param_PARAM_TAP_MS = 2,
    pyuron_gesture_Param_PARAM_THRESHOLD = 3,
    pyuron_gesture_Param_PARAM_MAX_THRESHOLD = 4
} pyuron_gesture_Param;

/* Struct definitions */
typedef struct _pyuron_gesture_GestureInfo {
    uint32_t id;
    pb_callback_t name;
    uint32_t tick;
    uint32_t wait_ms;
    uint32_t tap_ms;
    int32_t threshold;
    int32_t max_threshold;
} pyuron_gesture_GestureInfo;

typedef struct _pyuron_gesture_GetCountRequest {
    char dummy_field;
} pyuron_gesture_GetCountRequest;

typedef struct _pyuron_gesture_GetCountResponse {
    uint32_t count;
} pyuron_gesture_GetCountResponse;

typedef struct _pyuron_gesture_GetGestureRequest {
    uint32_t id;
} pyuron_gesture_GetGestureRequest;

typedef struct _pyuron_gesture_GetGestureResponse {
    bool has_gesture;
    pyuron_gesture_GestureInfo gesture;
} pyuron_gesture_GetGestureResponse;

typedef struct _pyuron_gesture_SetParamRequest {
    uint32_t id;
    pyuron_gesture_Param param;
    int32_t value;
} pyuron_gesture_SetParamRequest;

typedef struct _pyuron_gesture_SetParamResponse {
    bool has_gesture;
    pyuron_gesture_GestureInfo gesture;
} pyuron_gesture_SetParamResponse;

typedef struct _pyuron_gesture_ResetGestureRequest {
    uint32_t id;
} pyuron_gesture_ResetGestureRequest;

typedef struct _pyuron_gesture_ResetGestureResponse {
    bool has_gesture;
    pyuron_gesture_GestureInfo gesture;
} pyuron_gesture_ResetGestureResponse;

typedef struct _pyuron_gesture_Request {
    pb_size_t which_request_type;
    union {
        pyuron_gesture_GetCountRequest get_count;
        pyuron_gesture_GetGestureRequest get;
        pyuron_gesture_SetParamRequest set_param;
        pyuron_gesture_ResetGestureRequest reset;
    } request_type;
} pyuron_gesture_Request;

typedef struct _pyuron_gesture_ErrorResponse {
    pb_callback_t message;
} pyuron_gesture_ErrorResponse;

typedef struct _pyuron_gesture_Response {
    pb_size_t which_response_type;
    union {
        pyuron_gesture_ErrorResponse error;
        pyuron_gesture_GetCountResponse get_count;
        pyuron_gesture_GetGestureResponse get;
        pyuron_gesture_SetParamResponse set_param;
        pyuron_gesture_ResetGestureResponse reset;
    } response_type;
} pyuron_gesture_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pyuron_gesture_Param_MIN pyuron_gesture_Param_PARAM_TICK
#define _pyuron_gesture_Param_MAX pyuron_gesture_Param_PARAM_MAX_THRESHOLD
#define _pyuron_gesture_Param_ARRAYSIZE ((pyuron_gesture_Param)(pyuron_gesture_Param_PARAM_MAX_THRESHOLD+1))






#define pyuron_gesture_SetParamRequest_param_ENUMTYPE pyuron_gesture_Param








/* Initializer values for message structs */
#define pyuron_gesture_GestureInfo_init_default  {0, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define pyuron_gesture_GetCountRequest_init_default {0}
#define pyuron_gesture_GetCountResponse_init_default {0}
#define pyuron_gesture_GetGestureRequest_init_default {0}
#define pyuron_gesture_GetGestureResponse_init_default {false, pyuron_gesture_GestureInfo_init_default}
#define pyuron_gesture_SetParamRequest_init_default {0, _pyuron_gesture_Param_MIN, 0}
#define pyuron_gesture_SetParamResponse_init_default {false, pyuron_gesture_GestureInfo_init_default}
#define pyuron_gesture_ResetGestureRequest_init_default {0}
#define pyuron_gesture_ResetGestureResponse_init_default {false, pyuron_gesture_GestureInfo_init_default}
#define pyuron_gesture_Request_init_default      {0, {pyuron_gesture_GetCountRequest_init_default}}
#define pyuron_gesture_ErrorResponse_init_default {{{NULL}, NULL}}
#define pyuron_gesture_Response_init_default     {0, {pyuron_gesture_ErrorResponse_init_default}}
#define pyuron_gesture_GestureInfo_init_zero     {0, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define pyuron_gesture_GetCountRequest_init_zero {0}
#define pyuron_gesture_GetCountResponse_init_zero {0}
#define pyuron_gesture_GetGestureRequest_init_zero {0}
#define pyuron_gesture_GetGestureResponse_init_zero {false, pyuron_gesture_GestureInfo_init_zero}
#define pyuron_gesture_SetParamRequest_init_zero {0, _pyuron_gesture_Param_MIN, 0}
#define pyuron_gesture_SetParamResponse_init_zero {false, pyuron_gesture_GestureInfo_init_zero}
#define pyuron_gesture_ResetGestureRequest_init_zero {0}
#define pyuron_gesture_ResetGestureResponse_init_zero {false, pyuron_gesture_GestureInfo_init_zero}
#define pyuron_gesture_Request_init_zero         {0, {pyuron_gesture_GetCountRequest_init_zero}}
#define pyuron_gesture_ErrorResponse_init_zero   {{{NULL}, NULL}}
#define pyuron_gesture_Response_init_zero        {0, {pyuron_gesture_ErrorResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define pyuron_gesture_GestureInfo_id_tag        1
#define pyuron_gesture_GestureInfo_name_tag      2
#define pyuron_gesture_GestureInfo_tick_tag      3
#define pyuron_gesture_GestureInfo_wait_ms_tag   4
#define pyuron_gesture_GestureInfo_tap_ms_tag    5
#define pyuron_gesture_GestureInfo_threshold_tag 6
#define pyuron_gesture_GestureInfo_max_threshold_tag 7
#define pyuron_gesture_GetCountResponse_count_tag 1
#define pyuron_gesture_GetGestureRequest_id_tag  1
#define pyuron_gesture_GetGestureResponse_gesture_tag 1
#define pyuron_gesture_SetParamRequest_id_tag    1
#define pyuron_gesture_SetParamRequest_param_tag 2
#define pyuron_gesture_SetParamRequest_value_tag 3
#define pyuron_gesture_SetParamResponse_gesture_tag 1
#define pyuron_gesture_ResetGestureRequest_id_tag 1
#define pyuron_gesture_ResetGestureResponse_gesture_tag 1
#define pyuron_gesture_Request_get_count_tag     1
#define pyuron_gesture_Request_get_tag           2
#define pyuron_gesture_Request_set_param_tag     3
#define pyuron_gesture_Request_reset_tag         4
#define pyuron_gesture_ErrorResponse_message_tag 1
#define pyuron_gesture_Response_error_tag        1
#define pyuron_gesture_Response_get_count_tag    2
#define pyuron_gesture_Response_get_tag          3
#define pyuron_gesture_Response_set_param_tag    4
#define pyuron_gesture_Response_reset_tag        5

/* Struct field encoding specification for nanopb */
#define pyuron_gesture_GestureInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   tick,              3) \
X(a, STATIC,   SINGULAR, UINT32,   wait_ms,           4) \
X(a, STATIC,   SINGULAR, UINT32,   tap_ms,            5) \
X(a, STATIC,   SINGULAR, INT32,    threshold,         6) \
X(a, STATIC,   SINGULAR, INT32,    max_threshold,     7)
#define pyuron_gesture_GestureInfo_CALLBACK pb_default_field_callback
#define pyuron_gesture_GestureInfo_DEFAULT NULL

#define pyuron_gesture_GetCountRequest_FIELDLIST(X, a) \

#define pyuron_gesture_GetCountRequest_CALLBACK NULL
#define pyuron_gesture_GetCountRequest_DEFAULT NULL

#define pyuron_gesture_GetCountResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   count,             1)
#define pyuron_gesture_GetCountResponse_CALLBACK NULL
#define pyuron_gesture_GetCountResponse_DEFAULT NULL

#define pyuron_gesture_GetGestureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define pyuron_gesture_GetGestureRequest_CALLBACK NULL
#define pyuron_gesture_GetGestureRequest_DEFAULT NULL

#define pyuron_gesture_GetGestureResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gesture,           1)
#define pyuron_gesture_GetGestureResponse_CALLBACK NULL
#define pyuron_gesture_GetGestureResponse_DEFAULT NULL
#define pyuron_gesture_GetGestureResponse_gesture_MSGTYPE pyuron_gesture_GestureInfo

#define pyuron_gesture_SetParamRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    param,             2) \
X(a, STATIC,   SINGULAR, INT32,    value,             3)
#define pyuron_gesture_SetParamRequest_CALLBACK NULL
#define pyuron_gesture_SetParamRequest_DEFAULT NULL

#define pyuron_gesture_SetParamResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gesture,           1)
#define pyuron_gesture_SetParamResponse_CALLBACK NULL
#define pyuron_gesture_SetParamResponse_DEFAULT NULL
#define pyuron_gesture_SetParamResponse_gesture_MSGTYPE pyuron_gesture_GestureInfo

#define pyuron_gesture_ResetGestureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define pyuron_gesture_ResetGestureRequest_CALLBACK NULL
#define pyuron_gesture_ResetGestureRequest_DEFAULT NULL

#define pyuron_gesture_ResetGestureResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gesture,           1)
#define pyuron_gesture_ResetGestureResponse_CALLBACK NULL
#define pyuron_gesture_ResetGestureResponse_DEFAULT NULL
#define pyuron_gesture_ResetGestureResponse_gesture_MSGTYPE pyuron_gesture_GestureInfo

#define pyuron_gesture_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,get_count,request_type.get_count),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,get,request_type.get),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,set_param,request_type.set_param),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,reset,request_type.reset),   4)
#define pyuron_gesture_Request_CALLBACK NULL
#define pyuron_gesture_Request_DEFAULT NULL
#define pyuron_gesture_Request_request_type_get_count_MSGTYPE pyuron_gesture_GetCountRequest
#define pyuron_gesture_Request_request_type_get_MSGTYPE pyuron_gesture_GetGestureRequest
#define pyuron_gesture_Request_request_type_set_param_MSGTYPE pyuron_gesture_SetParamRequest
#define pyuron_gesture_Request_request_type_reset_MSGTYPE pyuron_gesture_ResetGestureRequest

#define pyuron_gesture_ErrorResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define pyuron_gesture_ErrorResponse_CALLBACK pb_default_field_callback
#define pyuron_gesture_ErrorResponse_DEFAULT NULL

#define pyuron_gesture_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,error,response_type.error),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,get_count,response_type.get_count),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,get,response_type.get),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,set_param,response_type.set_param),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,reset,response_type.reset),   5)
#define pyuron_gesture_Response_CALLBACK NULL
#define pyuron_gesture_Response_DEFAULT NULL
#define pyuron_gesture_Response_response_type_error_MSGTYPE pyuron_gesture_ErrorResponse
#define pyuron_gesture_Response_response_type_get_count_MSGTYPE pyuron_gesture_GetCountResponse
#define pyuron_gesture_Response_response_type_get_MSGTYPE pyuron_gesture_GetGestureResponse
#define pyuron_gesture_Response_response_type_set_param_MSGTYPE pyuron_gesture_SetParamResponse
#define pyuron_gesture_Response_response_type_reset_MSGTYPE pyuron_gesture_ResetGestureResponse

extern const pb_msgdesc_t pyuron_gesture_GestureInfo_msg;
extern const pb_msgdesc_t pyuron_gesture_GetCountRequest_msg;
extern const pb_msgdesc_t pyuron_gesture_GetCountResponse_msg;
extern const pb_msgdesc_t pyuron_gesture_GetGestureRequest_msg;
extern const pb_msgdesc_t pyuron_gesture_GetGestureResponse_msg;
extern const pb_msgdesc_t pyuron_gesture_SetParamRequest_msg;
extern const pb_msgdesc_t pyuron_gesture_SetParamResponse_msg;
extern const pb_msgdesc_t pyuron_gesture_ResetGestureRequest_msg;
extern const pb_msgdesc_t pyuron_gesture_ResetGestureResponse_msg;
extern const pb_msgdesc_t pyuron_gesture_Request_msg;
extern const pb_msgdesc_t pyuron_gesture_ErrorResponse_msg;
extern const pb_msgdesc_t pyuron_gesture_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pyuron_gesture_GestureInfo_fields &pyuron_gesture_GestureInfo_msg
#define pyuron_gesture_GetCountRequest_fields &pyuron_gesture_GetCountRequest_msg
#define pyuron_gesture_GetCountResponse_fields &pyuron_gesture_GetCountResponse_msg
#define pyuron_gesture_GetGestureRequest_fields &pyuron_gesture_GetGestureRequest_msg
#define pyuron_gesture_GetGestureResponse_fields &pyuron_gesture_GetGestureResponse_msg
#define pyuron_gesture_SetParamRequest_fields &pyuron_gesture_SetParamRequest_msg
#define pyuron_gesture_SetParamResponse_fields &pyuron_gesture_SetParamResponse_msg
#define pyuron_gesture_ResetGestureRequest_fields &pyuron_gesture_ResetGestureRequest_msg
#define pyuron_gesture_ResetGestureResponse_fields &pyuron_gesture_ResetGestureResponse_msg
#define pyuron_gesture_Request_fields &pyuron_gesture_Request_msg
#define pyuron_gesture_ErrorResponse_fields &pyuron_gesture_ErrorResponse_msg
#define pyuron_gesture_Response_fields &pyuron_gesture_Response_msg

/* Maximum encoded size of messages (where known) */
/* pyuron_gesture_GestureInfo_size depends on runtime parameters */
/* pyuron_gesture_GetGestureResponse_size depends on runtime parameters */
/* pyuron_gesture_SetParamResponse_size depends on runtime parameters */
/* pyuron_gesture_ResetGestureResponse_size depends on runtime parameters */
/* pyuron_gesture_ErrorResponse_size depends on runtime parameters */
/* pyuron_gesture_Response_size depends on runtime parameters */
#define PYURON_GESTURE_PYURON_GESTURE_GESTURE_PB_H_MAX_SIZE pyuron_gesture_Request_size
#define pyuron_gesture_GetCountRequest_size      0
#define pyuron_gesture_GetCountResponse_size     6
#define pyuron_gesture_GetGestureRequest_size    6
#define pyuron_gesture_Request_size              21
#define pyuron_gesture_ResetGestureRequest_size  6
#define pyuron_gesture_SetParamRequest_size      19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
